testing new workflow job rule

diff --git a/.github/workflows/default.yaml b/.github/workflows/default.yaml
--- a/.github/workflows/default.yaml
+++ b/.github/workflows/default.yaml
@@ -13,38 +13,69 @@ jobs:
     strategy:
       matrix:
         WORKDIR:
-                    - 8.0/alpine3.16
-          #          - 8.0/bullseye
-          #          - 8.1/alpine3.16
-          #          - 8.1/alpine3.17
-          #          - 8.1/bullseye
-          #          - 8.2/alpine3.17
-          #          - 8.2/bullseye
-        os: [ubuntu-latest, self-hosted]
+            - 8.0/alpine3.16
+#            - 8.0/bullseye
+#            - 8.1/alpine3.16
+#            - 8.1/alpine3.17
+#            - 8.1/bullseye
+#            - 8.2/alpine3.17
+#            - 8.2/bullseye
+        os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Prepare environment
-        run: bash ${GITHUB_WORKSPACE}/.github/scripts/prepare-workflow.sh
+#      - name: Prepare environment
+#        run: bash ${GITHUB_WORKSPACE}/.github/scripts/prepare-workflow.sh
 
-      - name: Build image
-        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
-        run: make build
+#      - name: Build image
+#        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
+#        run: make build
+#
+#      - name: Test image
+#        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
+#        run: make test
+#
+#      - name: Additional image tests
+#        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
+#        run: make official-test
+#
+#      - name: Display all docker images
+#        if: ${{ always() }}
+#        run: docker images
+#
+#      - name: Login to Docker Registry
+#        #        if: github.ref == 'refs/heads/v2'
+#        uses: docker/login-action@v1
+#        with:
+#          # We push to the default registry currently. If you want to push to a different registry,
+#          # uncomment the line below.
+#          # login-server: ${{ secrets.DOCKER_REGISTRY }}
+#          username: ${{ secrets.AMBIMAX_DOCKER_HUB_USERNAME }}
+#          password: ${{ secrets.AMBIMAX_DOCKER_HUB_PASSWORD }}
+#
+#      - name: Push image
+#        #        if: github.ref == 'refs/heads/v2'
+#        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
+#        run: make push-image
+#        env:
+#          DOCKER_USER: ${{ secrets.AMBIMAX_DOCKER_HUB_USERNAME }}
+#          DOCKER_PASSWORD: ${{ secrets.AMBIMAX_DOCKER_HUB_PASSWORD }}
 
-      - name: Test image
-        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
-        run: make test
-
-      - name: Additional image tests
-        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
-        run: make official-test
-
-      - name: Display all docker images
-        if: ${{ always() }}
-        run: docker images
-
+  build-manifests:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        REPOSITORY:
+          - php-8.0-alpine3.16
+          - php-8.0-bullseye
+          - php-8.1-alpine3.16
+          - php-8.1-alpine3.17
+          - php-8.1-bullseye
+          - php-8.2-alpine3.17
+          - php-8.2-bullseye
+    steps:
       - name: Login to Docker Registry
         #        if: github.ref == 'refs/heads/v2'
         uses: docker/login-action@v1
@@ -55,10 +86,32 @@ jobs:
           username: ${{ secrets.AMBIMAX_DOCKER_HUB_USERNAME }}
           password: ${{ secrets.AMBIMAX_DOCKER_HUB_PASSWORD }}
 
-      - name: Push image
-        #        if: github.ref == 'refs/heads/v2'
-        working-directory: 'dist/images/${{ matrix.WORKDIR }}'
-        run: make push-image
+      - name: test
         env:
-          DOCKER_USER: ${{ secrets.AMBIMAX_DOCKER_HUB_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.AMBIMAX_DOCKER_HUB_PASSWORD }}
+          REGISTRY: ambimax/${{ matrix.REPOSITORY }}
+        run: |
+          PHP_VERSION=$(echo "$REGISTRY" | awk -F'-' '{print $2}')
+
+          while read -r TAG; do
+            case "$TAG" in
+              *arm64|*aarch64)
+                ARM_TAG="$TAG"
+                ;;
+              *amd64|*x86_64)
+                AMD_TAG="$TAG"
+                ;;
+            esac
+          done < <(
+            curl -s "https://registry.hub.docker.com/v2/repositories/${REGISTRY}/tags?page_size=100" \
+            | jq -r '.results[].name' \
+            | grep "^$VERSION"
+          )
+
+          if [[ -z "$AMD_TAG" || -z "$ARM_TAG" ]]; then
+            echo "Missing tags for docker image artifact, registry: $REGISTRY"
+            exit 1
+          fi
+
+          echo "AMD: $AMD_TAG"
+          echo "ARM: $ARM_TAG"
+
